Error Page Tests
My-Budget-Buddy/Budget-Buddy-Frontend-Testing pull request #16
Opened 2024-09-19 21:08 UTC by Anthowu07

### Created 3 files
```
SDError.java
error.feature
ErrorPage.java
```

##Two Tests
- Check that the error page is displayed when entering an invalid URL
- Check that the user can be redirected to the landing page from the error page

2024-09-20 01:53 UTC, msabas1 requested changes

2024-09-20 01:53 UTC, msabas1 commented on cucumber-selenium-tests/src/test/java/com/skillstorm/Utilities/Navigator.java
> +    public static final String URL_ERROR= "http://localhost:5173/error";
For URL_ERROR, I'd suggest pulling latest and then using the convention of:
URL + "/error";

2024-09-20 01:53 UTC, msabas1 commented on cucumber-selenium-tests/src/test/java/com/skillstorm/PageObjects/ErrorPage.java
> +        throw new UnsupportedOperationException("Unimplemented method 'getChildComponents'");
I suggest returning null here if there aren't any child components related to the ErrorPage to avoid exceptions being thrown during test automation

2024-09-20 01:53 UTC, msabas1 commented on cucumber-selenium-tests/src/test/java/com/skillstorm/PageObjects/ErrorPage.java
> +        throw new UnsupportedOperationException("Unimplemented method 'getChildComponent'");
I suggest returning null here if there aren't any child components related to the ErrorPage to avoid exceptions being thrown during test automation

2024-09-20 19:36 UTC, MaelstromDef requested changes
I'm not really sure why it's showing the DashboardPage being added here, is that able to be fixed?

2024-09-21 01:23 UTC, msabas1 submitted a review, later dismissed

2024-09-23 13:35 UTC, MaelstromDef approved these changes, later dismissed
LGTM

2024-09-24 19:34 UTC, MaelstromDef requested changes
Please bring back DashboardPage

2024-09-24 19:47 UTC, MaelstromDef approved these changes
LGTM

2024-09-24 19:50 UTC, jmensah365 approved these changes

2024-09-24 19:50 UTC, Bryar-Frank approved these changes

2024-09-24 19:51 UTC, merged