Standardizing transaction pages
My-Budget-Buddy/Budget-Buddy-Frontend-Testing pull request #25
Opened 2024-09-23 23:00 UTC by jmensah365

2024-09-23 23:40 UTC, MaelstromDef requested changes
Incorrect target branch for pull request.

2024-09-24 00:09 UTC, msabas1 approved these changes, later dismissed
LGTM

2024-09-24 00:18 UTC, MaelstromDef requested changes
A few if statements are never run.

2024-09-24 00:18 UTC, MaelstromDef commented on cucumber-selenium-tests/src/test/java/com/skillstorm/PageObjects/TransactionHistoryPage.java
>      public String confirmCreation() {
Low impact: The 2nd, 3rd, and 4th if statements will never be run.
Suggestion: Reverse the order of the if statements or remove the unnecessary ones.

2024-09-24 00:18 UTC, MaelstromDef commented on cucumber-selenium-tests/src/test/java/com/skillstorm/PageObjects/TransactionPage.java
>      public String verifyTransactionDetails() {
Low impact: The 2nd, 3rd, and 4th if statements will never be run.
Suggestion: Reverse the order of the if statements or remove the unnecessary ones.

2024-09-24 01:11 UTC, MaelstromDef approved these changes, later dismissed
LGTM

2024-09-24 01:14 UTC, msabas1 approved these changes, later dismissed
LGTM

2024-09-24 15:55 UTC, msabas1 approved these changes
LGTM

2024-09-24 15:56 UTC, Aldrich19 approved these changes

2024-09-24 15:57 UTC, MaelstromDef approved these changes
LGTM

2024-09-24 16:08 UTC, merged